accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = "accounts"

urlpatterns = [
    path("register-user/", views.RegisterUser.as_view(), name="registerUser"),
    path("get-account-data/", views.UserProfileData.as_view(), name="getAccountData"),
    path("activate-user/<uidb64>/<token>/", views.activate, name="activateUser"),
    path('get-token/', views.GetToken.as_view(), name="getToken"),
    path('forgot-password/', views.ForgotPassword.as_view(), name="forgotPassword"),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name="resetPasswordValidate"),
    path('reset-password/', views.reset_password, name="resetPassword"),
]

drivelicense/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('', include("testapp.urls")),
]

testapp/urls.py
from django.urls import path
from . import views

app_name = "testapp"

urlpatterns = [
    path("exam-questions/<str:categoryName>/", views.GetExamQuestions.as_view(), name="examQuestions"),
    path("categories/", views.GetAllLicenseCategories.as_view(), name="licenseCategories"),
    path("test-media/<str:mediaType>/", views.TestMedia.as_view(), name="testMedia"),
    path("store-exam-result/", views.StoreExamResult.as_view(), name="examResult"),
    path("list-exam-result/", views.ListExamResult.as_view(), name="listExamResult"),
    path("delete-exam-result/<int:pk>/", views.DeleteExamResult.as_view(), name="deleteExamResult"),
    path("exam-result-details/<int:mainId>/", views.ExamDetails.as_view(), name="examResultDetails"),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from uuid import uuid4

class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name= "userprofile"
    )
    # pic = models.ImageField(upload_to="drivelicense-user-images/", default="test.jpg")
    stop_notification = models.BooleanField(default=False)
    bio = models.TextField(blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(
                user = instance
            )
            
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

    def __str__(self) -> str:
        return f"{self.stop_notification}, {self.bio}"

@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class ResetPasswordForm(forms.ModelForm):
    confirm_password = forms.CharField()

    class Meta:
        model = User
        fields = ("password", "confirm_password",)

accounts/views.py
from rest_framework.response import Response
from rest_framework import status, mixins, generics, permissions, filters
from rest_framework.views import APIView
from django.contrib.auth.models import User
from .serializers import UserRegisterSerializer, UserProfileSerializer
from django.conf import settings
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render
from rest_framework.authtoken.models import Token
from django.contrib.auth import authenticate
from .utils import send_reset_password_email
from .forms import ResetPasswordForm
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from testapp.permissions import IsOwnerUser

class RegisterUser(generics.CreateAPIView):
    serializer_class = UserRegisterSerializer
    permission_classes = [permissions.AllowAny,]

class UserProfileData(APIView):
    permission_classes = [IsOwnerUser]

    def get(self, request, format=None):
        user = self.request.user
        userprofile = user.userprofile
        serializer = UserProfileSerializer(userprofile)
        return Response(serializer.data)
    
def activate(request, uidb64, token): 
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, "activation_success.html", {"current_domain":settings.CURRENT_DOMAIN})
    else:
        return render(request, "activation_failed.html")

class GetToken(APIView):

    def post(self, request, format=None):
        username = request.data["email"]
        password = request.data["password"]

        user = authenticate(username=username, password=password)

        if user is not None:
            token, created = Token.objects.get_or_create(user=user)
            return Response({"token":f"{token}"}, status=status.HTTP_200_OK)
        
        else:
            #user = User.objects.get(username=username)
            user = User.objects.filter(username=username).exists()

            if not user :
                return Response({"error": "This user doens't exist."}, status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({"error": "This password is incorrect."}, status=status.HTTP_400_BAD_REQUEST)
            
class ForgotPassword(APIView):

    def post(self, request, format=None):
        email = request.data["email"]

        if User.objects.filter(username=email).exists():
            user = User.objects.get(username=email)
            send_reset_password_email(request,
                                      "Reset hasła",
                                      "reset_password_email.html",
                                      user,
                                      email)
            return Response({"message":"Wysłano link do zmiany hasła!"}, status=status.HTTP_200_OK)
        
        else:
            return Response({"error":"Taki użytkownik nie istnieje!"}, status=status.HTTP_400_BAD_REQUEST)

def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        return render(request, "reset_password.html")
    else:
        return render(request, "reset_password_failed_page.html")

def reset_password(request):  
    if request.method == "POST":
        form = ResetPasswordForm(request.POST)
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        if password==confirm_password:
            try:
                validate_password(password)
            except ValidationError as exceptions:
                return render(request, "reset_password.html", {"passError":exceptions,
                                                               "length": len(list(exceptions))})
            else:
                if form.is_valid():
                    uid = request.session.get("uid")
                    user = User.objects.get(pk = uid)
                    user.set_password(password)
                    user.save()
                    #return HttpResponse("success")
                    return render(request, "reset_password_success.html")
                
                else:
                    form = ResetPasswordForm()
        else:
            errorMsg = "Hasła nie są identyczne!"
            return render(request, "reset_password.html", {"errorMsg":errorMsg})
        
    context = {
        "form":form
    }

    return render(request, "reset_password.html", context)
    

            

accounts/templates/account_activation_email.html
{% autoescape off %}

Cześć,

Kliknij poniższy link, aby aktywować konto:
{{domain}}{% url 'accounts:activateUser' uidb64=uid token=token %}

Pozdrawiamy,
Zespół Prawko

{% endautoescape %}

accounts/templates/activation_failed.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'styles/img/samochodzik.jpg' %}">
    <style>

        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        html, body {
            font-size: 10px;
            font-weight: 400;
            font-family: 'Lato';
        }

        .row {
            max-width: 1140px;
            margin: 0 auto;
        }

        .failed{
            text-align: center;
            background-color: #f8d7da;
            padding: 2rem;
            border-radius: 0.5rem;
            margin: 6rem auto;
            position: absolute;
            top: 30%;
            left: 50%;
            transform: translate(-50%, -50%) scale(1);
        }

        .failed h3{
            font-size: 5rem;
            margin-bottom: 1.5rem;
            margin-top: 1.5rem;
        }

        .failed a{
            text-decoration: none;
            color: black;
            font-size: 3rem;
        }

        .failed a:hover{
            text-decoration: underline;
        }

        @media only screen and (max-width: 1220px){
 
        }

    </style>
    <title>Niepowodzenie</title>
</head>
<body>
    <div class="row">
        <div class="failed">
            <h3>Aktywacja konta nie powiodła się ! :(</h3>
            <a href="https://wiktorpiela.github.io/drive-license-exam-app-frontend/" target="_blank">Kliknij wrócić na stronę główną!</a>
        </div>
    </div>
    
</body>
</html>

accounts/templates/activation_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="static/img/samochodzik.jpg">
    <style>

        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        html, body {
            font-size: 10px;
            font-weight: 400;
            font-family: 'Lato';
        }

        .row {
            max-width: 1140px;
            margin: 0 auto;
        }

        .success{
            text-align: center;
            background-color: #d4edda;
            padding: 2rem;
            border-radius: 0.5rem;
            margin: 6rem auto;
            position: absolute;
            top: 30%;
            left: 50%;
            transform: translate(-50%, -50%) scale(1);
        }

        .success h3{
            font-size: 5rem;
            margin-bottom: 1.5rem;
            margin-top: 1.5rem;
        }

        .success a{
            text-decoration: none;
            color: black;
            font-size: 3rem;
        }

        .success a:hover{
            text-decoration: underline;
        }

        @media only screen and (max-width: 1220px){

            
        }

    </style>
    <title>Aktywacja konta</title>
</head>
<body>
    <div class="row">
        <div class="success">
            <img src="static/img/samochodzik.jpg" alt="pic">
            <h3>Konto zostało aktywowane !</h3>
            <a href="https://wiktorpiela.github.io/drive-license-exam-app-frontend/" target="_blank">Kliknij wrócić na stronę główną!</a>
        </div>
    </div>
</body>
</html>

accounts/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="static/img/samochodzik.jpg">
    <style>

        /* reusable */
        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        html, body {
            font-size: 10px;
            font-weight: 400;
            font-family: 'Lato';
        }

        .row {
            max-width: 1140px;
            margin: 0 auto;
        }

        .btn{
            color: #f7f7f7;
            background-color: #f0ad4e;
            border-radius: 0.3rem;
            border: none;
            padding: 1rem;
        }

        .btn:disabled,
        .btn:hover:disabled{
            background-color: #f7d19c;
        }

        .btn:hover{
            background-color: #c77c11;
        }

        .footer-content{
            display: flex;
            justify-content: space-around;
            font-size: 1.5rem;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            color: #829695;
            margin-bottom: 1rem;
        }

        .footer-content a{
            text-decoration: none;
            color: #829695
        }

        /* end reusable */

        .set-pass-div{
            font-size: 3.5rem;
            width: 40rem;
            margin: 0 auto;
            box-shadow: 2px 2px 2px 1px #777;
            margin-top: 10rem;
            border-radius: 0.3rem;
        }

        .above p{
            text-align: center;
            background-color: #f0ad4e;
            color: white;
            padding: 1rem;
        }

        .form-div form{
            display: flex;
            flex-direction: column;
        }

        .form-div{
            padding: 3rem;
            padding-top: 1.5rem;
            background-color: #ddd;
        }


        .form-div form input{
            margin-bottom: 1rem;
            font-size: 2rem;
            padding: 0.75rem;
            border-radius: 0.5rem;
            border: none;
        }

        .form-div form button{
            font-size: 2rem;
        }

        /* post-reset status */
        .set-pass-failed{
            background-color: #f8d7da;
            text-align: center;
            font-size: 2rem;
            margin-top: 6rem;
            padding: 1rem;
            border-radius: 0.5rem;
            margin: 6rem auto;
            width: 70rem;
        }

        .set-pass-failed ul{
            display: inline-block;
            text-align: left;
        }

        /* queries */
        @media only screen and (max-width: 710px){
            .set-pass-failed{
                width: 60rem;
            }
        }

        @media only screen and (max-width: 610px){
            .set-pass-failed{
                width: 50rem;
            }

            .set-pass-failed li{
                font-size: 1.7rem;
            }
        }

        @media only screen and (max-width: 510px){
            html, body {
                font-size: 9px;

            }
        }

        @media only screen and (max-width: 460px){
            html, body {
                font-size: 8px;
            }
        }

        @media only screen and (max-width: 410px){
            html, body {
                font-size: 7px;
            }
        }

        @media only screen and (max-width: 281px){
            html, body {
                font-size: 6px;
            }
        }
    </style>
    <title>Ustaw nowe hasło</title>
</head>
<body>
    <div class="row">
        <div class="set-pass-div">
            <div class="above">
                <p>Reset hasła</p>
            </div>
            <div class="form-div">
                <form action="{% url 'accounts:resetPassword' %}" method="post">
                    {% csrf_token %}
                    <input type="password" name="password" maxlength="150" autofocus="" required="" placeholder="Nowe hasło">
                    <input type="password" name="confirm_password" maxlength="150" autofocus="" required="" placeholder="Powtórz hasło">
                    <button type="submit" class="btn set-new-pass-btn">Ustaw</button>
                </form>     
            </div>
        </div>

        {% if passError %} 
            <div class="set-pass-failed">
                <ul>
                {% for err in passError  %}
                    <li>{{err}}</li>
                {% endfor %}  
                </ul>
            </div>  
        {% endif %}

        {% if errorMsg %}
        <div class="set-pass-failed">
            <p>{{errorMsg}}</p>
        </div>
        {% endif %}

    </div>

    <footer>
        <div class="footer-content">
            <p><ion-icon name="logo-github"></ion-icon><a href="https://github.com/wiktorpiela" target="_blank">Github repo</a></p>
            <p><ion-icon name="mail-outline"></ion-icon><a href="mailto:wpiela9@gmail.com">Contact me</a></p>
            <p><ion-icon name="logo-linkedin"></ion-icon><a href="https://www.linkedin.com/in/wiktor-p-44347b207/?originalSubdomain=pl" target="_blank">LinkedIn</a></p>
        </div>
    </footer>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

accounts/templates/reset_password_email.html
{% autoescape off %}

Cześć,

Kliknij poniższy link, aby zresetować hasło:
http://{{domain}}{% url 'accounts:resetPasswordValidate' uidb64=uid token=token %}

Pozdrawiamy,
Zespół Prawko

{% endautoescape %}

accounts/templates/reset_password_failed_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>password reset link expired - something went wrong</h1>
</body>
</html>

accounts/templates/reset_password_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
    <style>

        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        html, body {
            font-size: 10px;
            font-weight: 400;
            font-family: 'Lato';
        }

        .row {
            max-width: 1140px;
            margin: 0 auto;
        }

        .footer-content{
            display: flex;
            justify-content: space-around;
            font-size: 1.5rem;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            color: #829695;
            margin-bottom: 1rem;
        }

        .footer-content a{
            text-decoration: none;
            color: #829695
        }

        .set-pass-success{
            text-align: center;
            font-size: 2rem;
            margin-top: 6rem;
            background-color: #d4edda;
            padding: 1rem;
            border-radius: 0.5rem;
            margin: 6rem auto; 
        }

        .set-pass-success a{
            text-decoration: none;
        }

        /* queries */

        

    </style>
    <title>Hasło zmienione</title>
</head>
<body>
    <div class="row">
        <div class="set-pass-success">
            <h1>Hasło zostało zmienione pomyślnie!</h1>
            <a href="https://wiktorpiela.github.io/drive-license-exam-app-frontend/loginPage">Zaloguj się</a>
        </div>
    </div>

    <footer>
        <div class="footer-content">
            <p><ion-icon name="logo-github"></ion-icon><a href="https://github.com/wiktorpiela" target="_blank">Github repo</a></p>
            <p><ion-icon name="mail-outline"></ion-icon><a href="mailto:wpiela9@gmail.com">Contact me</a></p>
            <p><ion-icon name="logo-linkedin"></ion-icon><a href="https://www.linkedin.com/in/wiktor-p-44347b207/?originalSubdomain=pl" target="_blank">LinkedIn</a></p>
        </div>
    </footer>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>